//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegExAppeal.WebApp {
    
    
    public partial class _Default {
        
        /// <summary>
        /// gameBoard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RegExAppeal.WebApp.WebControls.GameBoard gameBoard;
        
        /// <summary>
        /// keyboard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RegExAppeal.WebApp.WebControls.Keyboard keyboard;
    }
}
